package org.example.WebDriver_Selenium.Labbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class Lab1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lab1() {
    driver.get("https://www.google.com/");
    driver.findElement(By.id("APjFqb")).sendKeys("Testing methods");
    driver.findElement(By.name("btnK")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".aTI8gc > div:nth-child(1)"));
      assert(elements.size() > 0);
    }
  }
}
