package org.example.WebDriver_Selenium.Labbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class Lab4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lab4() {
    driver.get("https://demo.opencart.com/");
    driver.findElement(By.linkText("Desktops")).click();
    driver.findElement(By.linkText("Mac (1)")).click();
    driver.findElement(By.id("input-sort")).click();
    {
      WebElement dropdown = driver.findElement(By.id("input-sort"));
      dropdown.findElement(By.xpath("//option[. = 'Name (A - Z)']")).click();
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("iMac"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".image .img-fluid")).click();
    driver.findElement(By.id("button-cart")).click();
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("search")).sendKeys("Monitor");
    driver.findElement(By.cssSelector(".btn-lg:nth-child(2)")).click();
    driver.findElement(By.id("input-description")).click();
    driver.findElement(By.id("button-search")).click();
  }
}
