CREATE TABLE IF NOT EXISTS bookstore (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    author_name VARCHAR(255),
    book_name VARCHAR(255),
    category VARCHAR(255),
    published_year VARCHAR(255),
    publisher VARCHAR(255),
    PRIMARY KEY (id)
    );
